### PR TITLE
Update Request API documentation

### PR DESCRIPTION
**Pull request by chekunkov**
'time' and 'method' fields are required.

### CODE REVIEW

**Comment by redapple** [comment]
+1 for python-hubstorage cleanups.
See https://github.com/scrapinghub/doc.scrapinghub.com/issues/156

**Comment by chekunkov** [comment]
@vshlapakov @redapple I'd prefer to remove python-hubstorage in a separate PR

**Comment by chekunkov** [comment]
Actually what if I remove python examples from this site completely? python-scrapinghub now has very good documentation with examples, it should be enough to mention it and give a link to Read The Docs. Otherwise we have 2 places with python examples which will go out of sync quickly. What do you think @vshlapakov @redapple ?

**Comment by chekunkov** [comment]
Just created PR https://github.com/scrapinghub/doc.scrapinghub.com/pull/163 to illustrate what I mean.

**Comment by vshlapakov** [comment]
@chekunkov I don't have any objections, makes sense to me. I'd set doc.sh.com as an only authoritative source describing our HTTP API, and python client docs should have references to it in corresponding sections.

**Pull request merged**
