### PR TITLE
Adding a note about CONNECT in the examples section

### PR DESCRIPTION
**Pull request by serhiy-yasko**
https://intranet.scrapinghub.com/issues/44122

### CODE REVIEW

**Comment by pablohoffman** [comment]
Now that we support the standard CONNECT mechanism, I think we should promote it as the recommended way to access https sites through Crawlera (provided it's well tested, of course).

I would even consider phasing out some of the other ways (which were meant to suplement the lack of CONNECT support), especially the (often confusing) `x-crawlera-use-https` header.

Generally speaking, we should aim to remove the "Working with HTTPS" section anymore. HTTPS shouldn't require special treatment anymore. 

cc @amleczko @qrilka @gatufo

**Comment by qrilka** [comment]
But @pablohoffman using custom certificate is special treatment, just another form of it :)

**Comment by pablohoffman** [comment]
Right, but adding a custom certificate is something well supported by all HTTP clients, whereas sending a custom header isn't. But fair point, we may need to leave the "working with HTTPS" section to explain about the custom CA certificate.

**Comment by edubecks** [comment]
@rdowinton can you review the PR? Or can you assign someone else to review? Thanks

**Comment by pablohoffman** [comment]
I believe @amleczko is the right person to review and merge this

**Comment by amleczko** [comment]
please squash commits to max. 2 that will include @serhiy-yasko and @edubecks changes only.

**Pull request merged**
