### PR TITLE
Removed Python Requests example from Crawlera doc

### PR DESCRIPTION
**Pull request by rdowinton**
At @serhiy-yasko 's request. Removed Python Requests example as it's confusing and doesn't work with API key.

### CODE REVIEW

**Comment by pablohoffman** [comment]
why not make it work instead? /cc @qrilka

**Comment by qrilka** [comment]
@pablohoffman do you think we need to create a PR replacing `and` with `or` here - https://github.com/kennethreitz/requests/blob/master/requests/adapters.py#L317 ?
We could but then we need to put a huge warning that the current versions of requests do not work with username or password missing from proxy auth

**Comment by redapple** [comment]
scrapy also has this problem (although there is a PR waiting https://github.com/scrapy/scrapy/pull/1313)

**Comment by dangra** [comment]
@redapple not anymore.

**Comment by pablohoffman** [comment]
please revert this after this is done: https://intranet.scrapinghub.com/issues/33882

**Comment by qrilka** [comment]
Just reverting it won't help - we need to add some dummy password also

**Comment by pablohoffman** [comment]
yeah, revert + add dummy pass

**Comment by qrilka** [comment]
And https://github.com/scrapinghub/crawlera/pull/444 is waiting for review

**Comment by qrilka** [comment]
As fix from that PR will be deployed soon - should we update the docs and add dummy passwords?
I've see also similar problems with empty password in other languages in Intercom

**Comment by pablohoffman** [comment]
https://intranet.scrapinghub.com/issues/33882 is merged, can we simplfiy the `requests` example now?

**Pull request merged**
