### PR TITLE
correct offset param name

### PR DESCRIPTION
**Pull request by demelziraptor**

### CODE REVIEW

**Comment by pablohoffman** [comment]
looks ok to me, can you merge @chekunkov ?

**Comment by immerrr** [comment]
`?offset=` parameter is dash specific, at least hubstorage & jobq use `?start=`

**Comment by chekunkov** [comment]
@immerrr is right. Hubstorage and `python-hubstorage` do not accept `offset` parameter. And taking in account that Dash for it's API often [maps](https://github.com/scrapinghub/dash/search?l=python&q=offset&type=Code&utf8=%E2%9C%93) `offset` args to `start` args and makes requests to Hubstorage - I think it's easier to deprecate `offset` parameter for Dash and user `start` parameter instead.

-1 to merge this so far.

**Comment by chekunkov** [comment]
> I think it's easier to deprecate offset parameter in Dash and use start parameter instead.

@pablohoffman ^ needs your response

**Comment by pablohoffman** [comment]
I'm OK with deprecating `offset` but it's unclear if we need to do anything on Dash side. Ultimately, what matters from a public POV is what OneAPI will accept.

**Comment by chekunkov** [comment]
current page lists 2 endpoints

```
dash.scrapinghub.com
storage.scrapinghub.com
```

Original description `start     The offset from which to start retrieving results.` matches `storage.scrapinghub.com`. Changed description `offset    The offset from which to start retrieving results.` matches `dash.scrapinghub.com`. We either need to deprecate offset parameter in Dash (because it means changes only in a [3 lines](https://github.com/scrapinghub/dash/search?l=python&q=offset&utf8=%E2%9C%93) in a single repository vs changing all endpoint in JobQ and Hubstorage) or change this page to describe `dash.scrapinghub.com` and `storage.scrapinghub.com` separately. I would go for changes on Dash side because it's easy to do and we can make change backwards compatible (support both `offset` and `start` but keep only `start` documented).

**Comment by pablohoffman** [comment]
old/obsolete pull request

**Pull request closed without merging**
