### PR TITLE
Restructured API documentation

### PR DESCRIPTION
**Pull request by rdowinton**
* Each API now has its own page with sections for each endpoint.
* API endpoint sections have tables for result fields, parameters, and methods. Examples using curl are shown for each method supported.
* The API overview page now lists the endpoints for each domain (dash.scrapinghub.com and storage.scrapinghub.com), and links the relevant Python libraries.

### CODE REVIEW

**Comment by redapple** [comment]
@rdowinton ,
I don't see `schedule.json` documented anymore.
is it deprecated?

**Comment by rdowinton** [comment]
@redapple it's not deprecated. I must have missed it when moving from the original doc. I've added it back in the same format as the others.

**Comment by redapple** [comment]
Thanks @rdowinton .
It would be good to take this opportunity to document `job_settings` parameter as JSON string to pass per-job settings.

**Comment by rdowinton** [comment]
Done. Also added a note on using spider arguments with it too.

**Comment by redapple** [comment]
thanks @rdowinton

**Pull request merged**
